package com.thegreatnovel.jingyouhealth.ui

import com.thegreatnovel.jingyouhealth.model.AppLanguage

private data class CoreTranslation(
    val en: String,
    val fr: String,
    val ar: String,
)

/** Strings shared by the core, sleep timing, and personal-model experiences. */
private val coreTranslations = mapOf(
    "可用组成" to CoreTranslation("Available components", "Composantes disponibles", "المكونات المتاحة"),
    "恢复参考正在建立" to CoreTranslation("Building your recovery reference", "Construction de votre référence de récupération", "جارٍ بناء مرجع التعافي الخاص بك"),
    "积累足够个人记录后，就能看见自己的恢复基线。" to CoreTranslation("Your recovery baseline appears when enough personal records are available.", "Votre référence de récupération apparaîtra avec suffisamment de données personnelles.", "سيظهر خط تعافيك المرجعي عند توفّر سجلات شخصية كافية."),
    "\${h}小时" to CoreTranslation("\${h} hours", "\${h} h", "\${h} ساعة"),
    "\${h}小时\${m}分钟" to CoreTranslation("\${h} h \${m} min", "\${h} h \${m} min", "\${h} س \${m} د"),
    "\${m}分钟" to CoreTranslation("\${m} min", "\${m} min", "\${m} د"),
    "秒" to CoreTranslation("sec", "s", "ث"),
    "日变化" to CoreTranslation("Daily change", "Variation quotidienne", "التغير اليومي"),
    "近 7 天均值" to CoreTranslation("7-day average", "Moyenne sur 7 jours", "متوسط 7 أيام"),
    "近 7 天波动" to CoreTranslation("7-day variability", "Variabilité sur 7 jours", "تباين 7 أيام"),
    "相对近 28 天基线" to CoreTranslation("Deviation from recent 28-day baseline", "Écart par rapport à la base récente de 28 jours", "الانحراف عن خط أساس آخر 28 يومًا"),
    "共同作用" to CoreTranslation("Combined effect", "Effet combiné", "التأثير المشترك"),
    "其他信号" to CoreTranslation("Other signal", "Autre signal", "إشارة أخرى"),
    "主页" to CoreTranslation("Home", "Accueil", "الرئيسية"),
    "身体" to CoreTranslation("Body", "Corps", "الجسم"),
    "安排我的主页" to CoreTranslation("Arrange my home", "Organiser mon accueil", "رتّب صفحتي الرئيسية"),
    "把睡眠、训练和真实感受放在一起看。" to CoreTranslation("Look at sleep, training, and how you actually feel together.", "Mettez en regard sommeil, entraînement et sensations réelles.", "انظر إلى النوم والتدريب وما تشعر به فعليًا معًا."),
    "把最晚入睡的四分之一夜晚单独看" to CoreTranslation("Look separately at the quarter of nights with the latest bedtimes", "Examiner séparément le quart des nuits aux couchers les plus tardifs", "انظر منفصلًا إلى ربع الليالي ذات أوقات النوم الأكثر تأخرًا"),
    "比较的是各组中位数，不是单独改变睡觉时间的实验。" to CoreTranslation("This compares group medians; it is not an experiment that changes bedtime alone.", "La comparaison porte sur les médianes des groupes ; ce n’est pas une expérience modifiant uniquement l’heure du coucher.", "هذه مقارنة بين وسيطي المجموعتين وليست تجربة تغيّر وقت النوم وحده."),
    "变化与近期统计" to CoreTranslation("Changes and recent statistics", "Variations et statistiques récentes", "التغيرات والإحصاءات الأخيرة"),
    "不足 1 秒" to CoreTranslation("Less than 1 second", "Moins d’une seconde", "أقل من ثانية واحدة"),
    "部分节假日样本较少，暂不单独估计。" to CoreTranslation("Some holiday samples are small, so they are not estimated separately yet.", "Certains échantillons de jours fériés sont trop petits pour une estimation séparée.", "بعض عينات العطلات صغيرة، لذلك لا نقدّرها منفردة حاليًا."),
    "查看全部信号" to CoreTranslation("View all signals", "Voir tous les signaux", "عرض كل الإشارات"),
    "查看组成与个人基线" to CoreTranslation("View components and personal baseline", "Voir les composantes et la base personnelle", "عرض المكوّنات وخط الأساس الشخصي"),
    "打开教练" to CoreTranslation("Open Coach", "Ouvrir le coach", "افتح المدرب"),
    "打乱一个信号后，预测会多错多少。条越长，模型越依赖它。" to CoreTranslation("How much more the prediction misses after shuffling one signal. Longer bars mean the model relies on it more.", "L’erreur supplémentaire après avoir mélangé un signal. Plus la barre est longue, plus le modèle en dépend.", "كم يزداد خطأ التنبؤ بعد خلط إشارة واحدة. كلما طال الشريط زاد اعتماد النموذج عليها."),
    "当前个人参考" to CoreTranslation("Current personal reference", "Référence personnelle actuelle", "المرجع الشخصي الحالي"),
    "当晚入睡相对个人习惯的偏晚幅度；该时刻已发生，clock 预设可用 lag0" to CoreTranslation("How much later that night’s bedtime was than your usual time; it has already happened, so the clock preset can use lag0.", "Écart de l’heure du coucher de cette nuit par rapport à votre habitude ; le moment est déjà passé, le préréglage clock peut donc utiliser lag0.", "مقدار تأخر وقت النوم في تلك الليلة عن عادتك؛ الوقت حدث بالفعل، لذا يمكن لإعداد clock استخدام lag0."),
    "多项信号接近平时，结合今天的感受安排活动。" to CoreTranslation("Several signals are close to usual; plan activity together with how you feel today.", "Plusieurs signaux sont proches de l’habitude ; adaptez l’activité à vos sensations du jour.", "عدة إشارات قريبة من المعتاد؛ خطط لنشاطك مع مراعاة شعورك اليوم."),
    "法国法定节假日" to CoreTranslation("Public holiday in France", "Jour férié en France", "عطلة رسمية في فرنسا"),
    "法国全国节假日" to CoreTranslation("French national holidays", "Jours fériés nationaux français", "العطلات الوطنية الفرنسية"),
    "分析方法" to CoreTranslation("Analysis method", "Méthode d’analyse", "منهج التحليل"),
    "分析时考虑法定假日，不包含地方节日或个人休假。" to CoreTranslation("The analysis considers public holidays, not local holidays or personal leave.", "L’analyse tient compte des jours fériés, sans inclure les fêtes locales ni les congés personnels.", "يأخذ التحليل العطلات الرسمية في الحسبان، ولا يشمل العطلات المحلية أو الإجازات الشخصية."),
    "个人基线：取记录日期前 42 个日历日的有效值中位数，至少 7 条才比较。它不是 Garmin HRV 基线或医学阈值。" to CoreTranslation("Personal baseline: the median of valid values in the 42 calendar days before the record date; comparison starts at 7 values. It is not Garmin’s HRV baseline or a medical threshold.", "Base personnelle : médiane des valeurs valides dans les 42 jours calendaires précédant la date du relevé ; la comparaison commence à 7 valeurs. Ce n’est ni la base VFC de Garmin ni un seuil médical.", "خط الأساس الشخصي: وسيط القيم الصالحة في 42 يومًا تقويميًا قبل تاريخ السجل؛ تبدأ المقارنة عند توفر 7 قيم. ليس هذا خط Garmin الأساسي لـ HRV ولا حدًا طبيًا."),
    "还在建立个人恢复基线" to CoreTranslation("Still building your personal recovery baseline", "Construction de votre base personnelle de récupération", "جارٍ بناء خط أساس التعافي الشخصي"),
    "恢复，由哪些信号组成" to CoreTranslation("Which signals make up recovery", "Quels signaux composent la récupération", "ما الإشارات التي تكوّن التعافي"),
    "恢复参考" to CoreTranslation("Recovery reference", "Référence de récupération", "مرجع التعافي"),
    "恢复概览" to CoreTranslation("Recovery overview", "Vue d’ensemble de la récupération", "نظرة عامة على التعافي"),
    "恢复线索" to CoreTranslation("Recovery clues", "Indices de récupération", "مؤشرات التعافي"),
    "基础记录来自 Garmin，内部负荷由 JingYou 计算。" to CoreTranslation("Base records come from Garmin; JingYou calculates internal load.", "Les données de base viennent de Garmin ; JingYou calcule la charge interne.", "تأتي السجلات الأساسية من Garmin ويحسب JingYou الحمل الداخلي."),
    "加入变化、均值和波动" to CoreTranslation("Add changes, averages, and variability", "Ajouter variations, moyennes et variabilité", "إضافة التغيرات والمتوسطات والتباين"),
    "将原始压力日期向后对齐到下一晚睡眠日，严格只使用前一天记录" to CoreTranslation("Shift the raw stress date forward to the following sleep date, using strictly the previous day’s record.", "Décaler la date du stress brut vers la nuit de sommeil suivante, en utilisant strictement le relevé de la veille.", "تُرحّل تاريخ الضغط الخام إلى تاريخ النوم التالي مع استخدام سجل اليوم السابق فقط."),
    "较晚入睡" to CoreTranslation("Later bedtime", "Coucher plus tardif", "وقت نوم متأخر"),
    "教练提问" to CoreTranslation("Ask Coach", "Question au coach", "سؤال للمدرب"),
    "节假日前一天" to CoreTranslation("Day before a holiday", "Veille d’un jour férié", "اليوم السابق لعطلة"),
    "今天，想问身体什么？" to CoreTranslation("What would you like to ask your body today?", "Que voulez-vous demander à votre corps aujourd’hui ?", "ماذا تريد أن تسأل جسمك اليوم؟"),
    "近期训练负荷" to CoreTranslation("Recent training load", "Charge d’entraînement récente", "حمل التدريب الأخير"),
    "扩展输入加入差分、近周均值与波动、相对近期基线的偏离。辅助特征按训练段覆盖筛选，缺失时只使用训练段均值。" to CoreTranslation("Extended inputs add differences, recent-week averages and variability, and deviations from the recent baseline. Auxiliary features are screened by training-period coverage; missing values use only the training-period mean.", "Les entrées étendues ajoutent différences, moyennes et variabilité récentes, ainsi que les écarts à la base récente. Les variables auxiliaires sont filtrées selon leur couverture d’entraînement ; les valeurs manquantes utilisent uniquement la moyenne d’entraînement.", "تضيف المدخلات الموسعة الفروق ومتوسطات وتقلبات الأسابيع الأخيرة والانحراف عن خط الأساس الحديث. تُنتقى الخصائص المساعدة حسب تغطية فترة التدريب؛ والقيم المفقودة تستخدم متوسط فترة التدريب فقط."),
    "每条是入睡到醒来的记录窗口，虚线是通常醒来的时刻。" to CoreTranslation("Each line is a recorded window from falling asleep to waking; the dashed line is your usual wake time.", "Chaque ligne représente la fenêtre enregistrée du coucher au réveil ; la ligne pointillée indique l’heure habituelle du réveil.", "يمثل كل خط نافذة مسجلة من النوم حتى الاستيقاظ؛ والخط المتقطع هو وقت استيقاظك المعتاد."),
    "每项都先与自己的历史比较，再组成恢复参考。" to CoreTranslation("Each signal is first compared with your own history, then combined into the recovery reference.", "Chaque signal est d’abord comparé à votre propre historique, puis combiné dans la référence de récupération.", "تُقارن كل إشارة أولًا بسجلك الشخصي ثم تُجمع في مرجع التعافي."),
    "哪些信号，对这个模型更重要？" to CoreTranslation("Which signals matter more to this model?", "Quels signaux comptent le plus pour ce modèle ?", "ما الإشارات الأهم لهذا النموذج؟"),
    "平时醒来时刻" to CoreTranslation("Usual wake time", "Heure habituelle du réveil", "وقت الاستيقاظ المعتاد"),
    "其他夜晚" to CoreTranslation("Other nights", "Autres nuits", "ليالٍ أخرى"),
    "前日静息心率的变化" to CoreTranslation("Previous-day resting-HR change", "Variation de la FC au repos la veille", "تغير نبض الراحة في اليوم السابق"),
    "前日压力的近周均值" to CoreTranslation("Previous-day recent-week stress average", "Moyenne récente du stress de la veille", "متوسط ضغط اليوم السابق في الأسبوع الأخير"),
    "前夜 HRV 的变化" to CoreTranslation("Previous-night HRV change", "Variation de la VFC de la nuit précédente", "تغير HRV في الليلة السابقة"),
    "前一日身体压力" to CoreTranslation("Previous-day body stress", "Stress corporel de la veille", "ضغط الجسم في اليوم السابق"),
    "曲线形状随背景变化，表示森林捕捉到了组合关系；仍要看复核表现。" to CoreTranslation("The curve changes with the background, suggesting the forest captured a combined relationship; check its evaluation performance too.", "La forme de la courbe varie selon le contexte, ce qui suggère que la forêt a capté une relation combinée ; vérifiez aussi ses résultats en validation.", "يتغير شكل المنحنى مع السياق، ما يشير إلى أن الغابة التقطت علاقة مركبة؛ راجع أداء التحقق أيضًا."),
    "色带按每一天此前 42 天重新计算，会随你的长期状态移动。" to CoreTranslation("The band is recalculated from the previous 42 days for each day and moves with your long-term state.", "La bande est recalculée chaque jour sur les 42 jours précédents et évolue avec votre état à long terme.", "يُعاد حساب النطاق لكل يوم من الأيام الـ42 السابقة ويتحرك مع حالتك طويلة الأمد."),
    "色带覆盖此前 42 天中间 50% 的有效读数，不是医学正常范围；竖线为中位数。" to CoreTranslation("The band covers the middle 50% of valid readings from the previous 42 days; it is not a medical normal range. The vertical line is the median.", "La bande couvre les 50 % centraux des relevés valides des 42 jours précédents ; ce n’est pas une plage médicale normale. La ligne verticale indique la médiane.", "يغطي النطاق نسبة الـ50٪ الوسطى من القراءات الصالحة في الأيام الـ42 السابقة؛ وليس نطاقًا طبيًا طبيعيًا. والخط العمودي هو الوسيط."),
    "色带是过去 42 天的平时范围，圆点是这次读数" to CoreTranslation("The band is your usual range from the past 42 days; the dot is this reading", "La bande est votre plage habituelle des 42 derniers jours ; le point est le relevé actuel", "النطاق هو مجالك المعتاد خلال آخر 42 يومًا؛ والنقطة هي القراءة الحالية"),
    "上移" to CoreTranslation("Move up", "Monter", "تحريك لأعلى"),
    "身体信号" to CoreTranslation("Body signals", "Signaux corporels", "إشارات الجسم"),
    "身体状态" to CoreTranslation("Body state", "État du corps", "حالة الجسم"),
    "时长和占比要一起看：少睡可能缩短某个阶段，但不一定改变它的占比。" to CoreTranslation("Read duration and share together: less sleep may shorten a stage without necessarily changing its share.", "Lisez durée et proportion ensemble : dormir moins peut raccourcir une phase sans forcément modifier sa proportion.", "اقرأ المدة والنسبة معًا: قلة النوم قد تقصر مرحلة ما دون أن تغيّر نسبتها بالضرورة."),
    "使用此前 42 天个人基线；HRV 看近 7 天，静息心率看近 3 天。睡眠同时考虑这一晚和近 3 晚，负荷看近 3 天相对过去 28 天。" to CoreTranslation("Use the personal baseline from the previous 42 days; HRV uses the last 7 days and resting HR the last 3. Sleep considers this night and the last 3 nights; load uses the last 3 days against the previous 28.", "Utilise la base personnelle des 42 jours précédents ; la VFC porte sur les 7 derniers jours et la FC au repos sur les 3 derniers. Le sommeil tient compte de cette nuit et des 3 précédentes ; la charge compare les 3 derniers jours aux 28 précédents.", "استخدم خط الأساس الشخصي للأيام الـ42 السابقة؛ ويستخدم HRV آخر 7 أيام ونبض الراحة آخر 3. يأخذ النوم هذه الليلة وآخر 3 ليالٍ؛ ويقارن الحمل آخر 3 أيام بالـ28 السابقة."),
    "睡眠储备" to CoreTranslation("Sleep reserve", "Réserve de sommeil", "احتياطي النوم"),
    "睡眠占 40%，夜间 HRV 占 30%，静息心率占 20%，近期训练负荷占 10%。缺少的部分不补造，会调整可用权重。" to CoreTranslation("Sleep is 40%, overnight HRV 30%, resting HR 20%, and recent training load 10%. Missing parts are not invented; available weights are adjusted.", "Sommeil 40 %, VFC nocturne 30 %, FC au repos 20 % et charge récente 10 %. Les éléments manquants ne sont pas inventés ; les poids disponibles sont ajustés.", "النوم 40٪، وHRV الليلي 30٪، ونبض الراحة 20٪، وحمل التدريب الأخير 10٪. لا نختلق الأجزاء المفقودة؛ بل نعدّل الأوزان المتاحة."),
    "随机森林使用 32 棵浅树、最大深度 3、叶节点至少 8 条记录；不使用复核期调参数。" to CoreTranslation("The random forest uses 32 shallow trees, maximum depth 3, and at least 8 records per leaf; evaluation data is not used to tune it.", "La forêt aléatoire utilise 32 arbres peu profonds, une profondeur maximale de 3 et au moins 8 relevés par feuille ; les données de validation ne servent pas au réglage.", "تستخدم الغابة العشوائية 32 شجرة ضحلة، وعمقًا أقصى 3، وثمانية سجلات على الأقل لكل ورقة؛ ولا تُستخدم بيانات التحقق لضبطها."),
    "探索 REM 的因素" to CoreTranslation("Explore factors related to REM", "Explorer les facteurs liés au sommeil paradoxal", "استكشف عوامل نوم REM"),
    "探索深睡的因素" to CoreTranslation("Explore factors related to deep sleep", "Explorer les facteurs liés au sommeil profond", "استكشف عوامل النوم العميق"),
    "通常入睡" to CoreTranslation("Usual bedtime", "Heure habituelle du coucher", "وقت النوم المعتاد"),
    "通常醒来" to CoreTranslation("Usual wake time", "Heure habituelle du réveil", "وقت الاستيقاظ المعتاد"),
    "晚睡，醒来会一起推迟吗？" to CoreTranslation("If bedtime is later, does waking shift later too?", "Si le coucher est plus tardif, le réveil l’est-il aussi ?", "إذا تأخر وقت النوم، هل يتأخر الاستيقاظ أيضًا؟"),
    "晚睡幅度" to CoreTranslation("Bedtime delay", "Décalage du coucher", "تأخر وقت النوم"),
    "我们的恢复参考怎么算" to CoreTranslation("How is our recovery reference calculated?", "Comment calculons-nous la référence de récupération ?", "كيف نحسب مرجع التعافي؟"),
    "下移" to CoreTranslation("Move down", "Descendre", "تحريك لأسفل"),
    "心率变异恢复" to CoreTranslation("HRV recovery", "Récupération de la VFC", "تعافي HRV"),
    "醒来更晚" to CoreTranslation("Wake later", "Réveil plus tardif", "استيقاظ متأخر"),
    "醒来更早" to CoreTranslation("Wake earlier", "Réveil plus précoce", "استيقاظ أبكر"),
    "需要更多明确的当地入睡与醒来记录，才能查看这个作息窗口。" to CoreTranslation("More clear local bedtime and wake-time records are needed to view this sleep-timing window.", "Il faut davantage de relevés locaux clairs du coucher et du réveil pour afficher cette fenêtre de rythme.", "نحتاج إلى مزيد من السجلات المحلية الواضحة لوقت النوم والاستيقاظ لعرض نافذة توقيت النوم هذه."),
    "选择想看的模块，再调整它们的顺序。五个主要页面始终保留。" to CoreTranslation("Choose the modules you want to see, then reorder them. The five main pages always remain.", "Choisissez les modules à afficher, puis réorganisez-les. Les cinq pages principales restent toujours disponibles.", "اختر الوحدات التي تريد رؤيتها ثم غيّر ترتيبها. تبقى الصفحات الرئيسية الخمس محفوظة دائمًا."),
    "有些信号低于平时，给恢复多留一点空间。" to CoreTranslation("Some signals are below usual; leave a little more room for recovery.", "Certains signaux sont sous l’habitude ; laissez un peu plus de place à la récupération.", "بعض الإشارات أقل من المعتاد؛ اترك مساحة أكبر قليلًا للتعافي."),
    "这次回看中，森林比线性参考更贴近记录" to CoreTranslation("In this evaluation, the forest is closer to the records than the linear reference", "Dans cette validation, la forêt est plus proche des relevés que la référence linéaire", "في هذا التحقق، كانت الغابة أقرب إلى السجلات من المرجع الخطي"),
    "这次回看中，森林还没有超过线性参考" to CoreTranslation("In this evaluation, the forest has not yet exceeded the linear reference", "Dans cette validation, la forêt n’a pas encore dépassé la référence linéaire", "في هذا التحقق، لم تتجاوز الغابة المرجع الخطي بعد"),
    "这个模型尚未超过简单参考，重要性先作探索。" to CoreTranslation("This model has not yet exceeded the simple reference; treat importance as exploratory.", "Ce modèle n’a pas encore dépassé la référence simple ; l’importance reste exploratoire.", "لم يتجاوز هذا النموذج المرجع البسيط بعد؛ لذا اعتبر الأهمية استكشافية."),
    "这是有依据的信号组成的初始参考规则，不是已有临床验证的统一量表，也不是 Garmin 准备度。" to CoreTranslation("This is an initial reference rule built from evidence-based signals, not a clinically validated universal scale or Garmin readiness.", "Il s’agit d’une règle de référence initiale fondée sur des signaux étayés, pas d’une échelle universelle validée cliniquement ni de la préparation Garmin.", "هذه قاعدة مرجعية أولية مبنية على إشارات مدعومة، وليست مقياسًا موحدًا مثبتًا سريريًا ولا جاهزية Garmin."),
    "这是预测贡献，不是原因占比。相关信号会分摊信息；负数表示打乱后反而更准。" to CoreTranslation("This is predictive contribution, not a share of causes. Correlated signals share information; a negative value means shuffling made the prediction better.", "Il s’agit d’une contribution prédictive, pas d’une part causale. Les signaux corrélés se partagent l’information ; une valeur négative signifie que le mélange a amélioré la prédiction.", "هذه مساهمة تنبؤية وليست نسبة للأسباب. تتشارك الإشارات المترابطة المعلومات؛ والقيمة السالبة تعني أن الخلط حسّن التنبؤ."),
    "这些夜晚的典型入睡时间更晚" to CoreTranslation("These nights typically had later bedtimes", "Ces nuits avaient généralement des couchers plus tardifs", "كانت أوقات النوم في هذه الليالي متأخرة عادةً"),
    "整体接近平时，留意疲劳与睡眠时长。" to CoreTranslation("Overall close to usual; pay attention to fatigue and sleep duration.", "Globalement proche de l’habitude ; soyez attentif à la fatigue et à la durée du sommeil.", "الوضع قريب من المعتاد إجمالًا؛ انتبه للتعب ومدة النوم."),
    "只使用目标日前 42 天习惯醒来时刻，不使用目标夜实际醒来时间" to CoreTranslation("Use only the habitual wake time from the 42 days before the target date, not the target night’s actual wake time.", "Utiliser uniquement l’heure habituelle du réveil des 42 jours précédant la date cible, pas le réveil réel de la nuit cible.", "استخدم وقت الاستيقاظ المعتاد من الأيام الـ42 قبل التاريخ المستهدف فقط، ولا تستخدم وقت الاستيقاظ الفعلي في الليلة المستهدفة."),
    "重要性在留出的日期上按日历周打乱信号，重复 12 次。它不是树的原因贡献，也不是置信区间。" to CoreTranslation("Importance shuffles signals by calendar week on held-out dates, repeated 12 times. It is not a tree-based causal contribution or a confidence interval.", "L’importance mélange les signaux par semaine calendaire sur les dates laissées de côté, 12 fois. Ce n’est ni une contribution causale de l’arbre ni un intervalle de confiance.", "تخلط الأهمية الإشارات حسب الأسبوع التقويمي في التواريخ المحجوزة، وتكرر ذلك 12 مرة. وليست مساهمة سببية للشجرة ولا مجال ثقة."),
    "JingYou 恢复参考" to CoreTranslation("JingYou recovery reference", "Référence de récupération JingYou", "مرجع تعافي JingYou"),
    "按日历日期连接；缺少日期时会断开，不把间隔填成连续记录。" to CoreTranslation("Connect by calendar date; gaps stay breaks instead of being filled as continuous records.", "Relier par date calendaire ; les dates manquantes restent des ruptures et ne sont pas remplies.", "تُوصل حسب التاريخ التقويمي؛ وتبقى التواريخ المفقودة فواصل ولا تُملأ كسجلات متصلة."),
    "继续积累可比较的夜晚后，再回来查看变量权重。" to CoreTranslation("Build more comparable nights, then return to review feature weights.", "Accumulez davantage de nuits comparables, puis revenez voir les poids des variables.", "اجمع مزيدًا من الليالي القابلة للمقارنة ثم عد لمراجعة أوزان المتغيرات."),
    "交给教练解读" to CoreTranslation("Ask Coach to interpret", "Demander une interprétation au coach", "اطلب من المدرب التفسير"),
    "模型预测" to CoreTranslation("Model prediction", "Prédiction du modèle", "تنبؤ النموذج"),
    "目前还没有足够记录支持这个目标的机器学习线索" to CoreTranslation("There are not enough records yet to support machine-learning clues for this target.", "Il n’y a pas encore assez de relevés pour soutenir des indices d’apprentissage automatique pour cet objectif.", "لا توجد سجلات كافية بعد لدعم مؤشرات تعلم آلي لهذا الهدف."),
    "目前线索还不稳定" to CoreTranslation("The clues are not stable yet", "Les indices ne sont pas encore stables", "المؤشرات غير مستقرة بعد"),
    "请帮我解读这组睡眠洞察，区分记录支持的线索与尚待验证的假设。" to CoreTranslation("Help me interpret these sleep insights, separating clues supported by the records from hypotheses that still need testing.", "Aidez-moi à interpréter ces observations sur le sommeil, en séparant les indices soutenus par les relevés des hypothèses à vérifier.", "ساعدني في تفسير رؤى النوم هذه، مع فصل المؤشرات التي تدعمها السجلات عن الفرضيات التي تحتاج إلى تحقق."),
    "时长" to CoreTranslation("Duration", "Durée", "المدة"),
    "实际记录" to CoreTranslation("Actual records", "Relevés réels", "السجلات الفعلية"),
    "睡眠洞察" to CoreTranslation("Sleep insights", "Observations sur le sommeil", "رؤى النوم"),
    "线索可以继续观察" to CoreTranslation("These clues are worth observing further", "Ces indices peuvent continuer à être observés", "يمكن مواصلة مراقبة هذه المؤشرات"),
    "占比" to CoreTranslation("Share", "Proportion", "النسبة"),
    "这个日期还没有可用的睡眠洞察记录。" to CoreTranslation("There are no usable sleep-insight records for this date.", "Aucun relevé exploitable d’observations sur le sommeil pour cette date.", "لا توجد سجلات رؤى نوم قابلة للاستخدام لهذا التاريخ."),
    "这些线索靠得住吗？" to CoreTranslation("How reliable are these clues?", "Quelle est la fiabilité de ces indices ?", "ما مدى موثوقية هذه المؤشرات؟"),
    "这组线索还没有超过简单参考" to CoreTranslation("This set of clues has not exceeded the simple reference yet", "Ces indices n’ont pas encore dépassé la référence simple", "لم تتجاوز هذه المؤشرات المرجع البسيط بعد"),
    "这组线索在留出记录上比简单参考更贴近" to CoreTranslation("This set of clues is closer than the simple reference on held-out records", "Ces indices sont plus proches que la référence simple sur les relevés laissés de côté", "هذه المؤشرات أقرب من المرجع البسيط في السجلات المحجوزة"),
    "整体睡眠" to CoreTranslation("Overall sleep", "Sommeil global", "النوم الإجمالي"),
    "正在更新睡眠线索" to CoreTranslation("Updating sleep clues", "Mise à jour des indices de sommeil", "جارٍ تحديث مؤشرات النوم"),
    "正在寻找可解释的睡眠线索" to CoreTranslation("Looking for explainable sleep clues", "Recherche d’indices de sommeil explicables", "جارٍ البحث عن مؤشرات نوم قابلة للتفسير"),
    "机器学习方法" to CoreTranslation("Machine-learning method", "Méthode d’apprentissage automatique", "طريقة التعلم الآلي"),
    "模型平均相差" to CoreTranslation("Model average error", "Erreur moyenne du modèle", "متوسط خطأ النموذج"),
    "简单参考平均相差" to CoreTranslation("Simple-reference average error", "Erreur moyenne de la référence simple", "متوسط خطأ المرجع البسيط"),
    "用于复核的夜晚" to CoreTranslation("Nights used for evaluation", "Nuits utilisées pour la validation", "الليالي المستخدمة للتحقق"),
)

internal fun translateCore(language: AppLanguage, source: String): String? {
    val translation = coreTranslations[source] ?: return null
    return when (language) {
        AppLanguage.CHINESE -> source
        AppLanguage.ENGLISH -> translation.en
        AppLanguage.FRENCH -> translation.fr
        AppLanguage.ARABIC -> translation.ar
    }
}
