package com.thegreatnovel.jingyouhealth.ui

import com.thegreatnovel.jingyouhealth.model.AppLanguage

private data class InsightTranslation(val en: String, val fr: String, val ar: String)

private val insightTranslations = mapOf(
    "这一晚，发生了什么" to InsightTranslation("What happened that night", "Que s’est-il passé cette nuit-là ?", "ماذا حدث في تلك الليلة؟"),
    "等待睡眠数据" to InsightTranslation("Waiting for sleep data", "En attente des données de sommeil", "بانتظار بيانات النوم"),
    "睡眠评分" to InsightTranslation("Sleep score", "Score de sommeil", "درجة النوم"),
    "为什么没睡好？从这里开始" to InsightTranslation("Slept poorly? Start here", "Mal dormi ? Commencez ici", "لم تنم جيدًا؟ ابدأ من هنا"),
    "请复盘这晚睡眠，结合前一天压力、同夜 HRV 和静息心率，区分观测、相关性和待验证原因。" to InsightTranslation("Review this night’s sleep alongside the preceding day’s stress, same-night HRV, and resting heart rate. Separate observations, associations, and possible causes that still need checking.", "Analysez cette nuit de sommeil en tenant compte du stress de la veille, de la VFC de la même nuit et de la fréquence cardiaque au repos. Distinguez les observations, les corrélations et les causes possibles restant à vérifier.", "راجع نوم هذه الليلة مع إجهاد اليوم السابق وتقلّب معدل ضربات القلب في الليلة نفسها ونبض الراحة. ميّز بين الملاحظات والارتباطات والأسباب المحتملة التي تحتاج إلى التحقق."),
    "睡眠记录日期" to InsightTranslation("Sleep record date", "Date du relevé de sommeil", "تاريخ سجل النوم"),
    "睡眠复盘" to InsightTranslation("Sleep review", "Bilan du sommeil", "مراجعة النوم"),
    "这一晚，尚待了解" to InsightTranslation("This night is still a question", "Cette nuit reste à comprendre", "ما زلنا نحتاج إلى فهم هذه الليلة"),
    "这一晚，比平时短一些" to InsightTranslation("A little less sleep than usual", "Une nuit un peu plus courte", "نوم أقصر قليلًا من المعتاد"),
    "这一晚，比平时长一些" to InsightTranslation("A little more sleep than usual", "Une nuit un peu plus longue", "نوم أطول قليلًا من المعتاد"),
    "时长接近你的平时" to InsightTranslation("Close to your usual duration", "Une durée proche de vos habitudes", "مدة قريبة من المعتاد"),
    "从这一晚，了解自己" to InsightTranslation("Get to know yourself, one night at a time", "Mieux vous connaître, une nuit à la fois", "تعرّف على نفسك، ليلة بعد ليلة"),
    "实际睡眠" to InsightTranslation("Time asleep", "Temps de sommeil", "مدة النوم الفعلية"),
    "Garmin 评分 / 100" to InsightTranslation("Garmin score / 100", "Score Garmin / 100", "درجة Garmin / 100"),
    "分数和感受不必一致。先看记录，再寻找线索。" to InsightTranslation("Your score and how you feel may differ. Start with the record, then look for clues.", "Le score et votre ressenti peuvent différer. Regardez d’abord les données, puis cherchez des pistes.", "قد تختلف الدرجة عن شعورك. ابدأ بالسجل، ثم ابحث عن مؤشرات."),
    "和自己的平时相比" to InsightTranslation("Compared with your usual", "Par rapport à vos habitudes", "مقارنةً بمعتادك"),
    "此前 28 天的中位数，不含这一晚" to InsightTranslation("Median of the preceding 28 days, excluding this night", "Médiane des 28 jours précédents, hors cette nuit", "وسيط الأيام الـ28 السابقة، دون هذه الليلة"),
    "同夜 HRV" to InsightTranslation("Same-night HRV", "VFC de la même nuit", "HRV في الليلة نفسها"),
    "醒来当天静息心率" to InsightTranslation("Resting HR on waking day", "FC au repos le jour du réveil", "نبض الراحة في يوم الاستيقاظ"),
    "前一天压力" to InsightTranslation("Previous-day stress", "Stress de la veille", "إجهاد اليوم السابق"),
    "睡眠的组成" to InsightTranslation("What your sleep is made of", "La composition de votre sommeil", "مكوّنات نومك"),
    "阶段总量，不是整夜时间线" to InsightTranslation("Stage totals, not a timeline of the night", "Durées des phases, sans chronologie de la nuit", "إجمالي مراحل النوم، وليس تسلسلها خلال الليل"),
    "寻找反复出现的联动" to InsightTranslation("Look for recurring connections", "Repérer les liens récurrents", "ابحث عن العلاقات المتكررة"),
    "睡眠时长与其他信号的个人历史关系" to InsightTranslation("How sleep duration relates to your other signals over time", "Liens entre la durée du sommeil et vos autres indicateurs dans le temps", "العلاقة بين مدة النوم ومؤشراتك الأخرى عبر الوقت"),
    "把感受也带进来" to InsightTranslation("Make room for how you feel", "Ajoutez aussi votre ressenti", "أضف ما تشعر به أيضًا"),
    "手表看不到的部分，可以告诉教练" to InsightTranslation("Tell your coach what your watch cannot see", "Dites au coach ce que la montre ne peut pas voir", "أخبر المدرب بما لا تراه الساعة"),
    "睡够了，还是觉得累" to InsightTranslation("I slept enough, but still feel tired", "J’ai assez dormi, mais je me sens encore fatigué", "نمت بما يكفي، لكنني ما زلت أشعر بالتعب"),
    "睡前发生了什么" to InsightTranslation("What happened before bed", "Ce qui s’est passé avant le coucher", "ما حدث قبل النوم"),
    "今晚可以试着调整什么" to InsightTranslation("What could I try changing tonight?", "Que pourrais-je ajuster ce soir ?", "ما الذي يمكنني تجربته بشكل مختلف الليلة؟"),
    "带着这些数据问教练" to InsightTranslation("Ask your coach with these details", "Interroger le coach avec ces données", "اسأل المدرب بهذه البيانات"),
    "平时" to InsightTranslation("Usual", "Habituellement", "المعتاد"),
    "基线需要至少 7 条有效记录" to InsightTranslation("A baseline needs at least 7 valid records", "La référence nécessite au moins 7 relevés valides", "يتطلب الخط المرجعي 7 سجلات صالحة على الأقل"),
    "深睡" to InsightTranslation("Deep", "Profond", "نوم عميق"),
    "浅睡" to InsightTranslation("Light sleep", "Sommeil léger", "نوم خفيف"),
    "清醒" to InsightTranslation("Awake", "Éveil", "يقظة"),
    "深睡与 REM 占实际睡眠的比例；清醒占睡眠与清醒总时长的比例。缺失数据保留为空。" to InsightTranslation("Deep and REM shares use time asleep. Awake share uses the combined asleep and awake duration. Missing values stay empty.", "Les parts de sommeil profond et paradoxal sont rapportées au temps de sommeil. La part d’éveil est rapportée au total sommeil et éveil. Les données manquantes restent vides.", "تُحسب حصتا النوم العميق ونوم REM من مدة النوم الفعلية، وحصة اليقظة من مجموع مدتي النوم واليقظة. تبقى القيم المفقودة فارغة."),
    "配对记录" to InsightTranslation("Paired records", "Relevés appariés", "السجلات المتطابقة"),
    "暂不足以解读" to InsightTranslation("Not enough to interpret yet", "Pas encore assez pour interpréter", "لا تكفي للتفسير بعد"),
    "线性关系较弱" to InsightTranslation("Weak linear relationship", "Relation linéaire faible", "علاقة خطية ضعيفة"),
    "倾向同向变化" to InsightTranslation("Tend to move together", "Tendance à évoluer dans le même sens", "يميلان إلى التغيّر في الاتجاه نفسه"),
    "倾向反向变化" to InsightTranslation("Tend to move in opposite directions", "Tendance à évoluer en sens opposé", "يميلان إلى التغيّر في اتجاهين متعاكسين"),
    "相关不等于原因。至少 14 对记录才显示 r；日期缺失不填补，同夜信号可能共享测量来源。" to InsightTranslation("Association is not causation. r appears only with at least 14 pairs. Missing dates are not filled in; same-night signals may share measurement inputs.", "Une corrélation n’établit pas une cause. r n’apparaît qu’à partir de 14 paires. Les dates manquantes ne sont pas complétées ; les signaux d’une même nuit peuvent partager des mesures sources.", "الارتباط لا يثبت السبب. تظهر قيمة r عند توفر 14 زوجًا على الأقل. لا تُستكمل التواريخ المفقودة، وقد تشترك مؤشرات الليلة نفسها في مصادر القياس."),
    "指标探索" to InsightTranslation("Explore your metrics", "Explorer vos indicateurs", "استكشف مؤشراتك"),
    "从趋势走向理解" to InsightTranslation("From trends to understanding", "Des tendances à la compréhension", "من الاتجاهات إلى الفهم"),
    "天" to InsightTranslation("days", "jours", "يومًا"),
    "滑动查看每一天" to InsightTranslation("Slide to explore each day", "Faites glisser pour voir chaque jour", "مرّر لعرض كل يوم"),
    "有效记录" to InsightTranslation("Valid records", "Relevés valides", "السجلات الصالحة"),
    "范围" to InsightTranslation("Range", "Étendue", "النطاق"),
    "打开最近一晚复盘" to InsightTranslation("Review the latest night", "Voir le bilan de la dernière nuit", "راجع آخر ليلة مسجّلة"),
    "请解释这个指标的近期变化、计算方法及与睡眠的关系。" to InsightTranslation("Explain this metric’s recent changes, how it is calculated, and how it relates to sleep.", "Expliquez l’évolution récente de cet indicateur, sa méthode de calcul et son lien avec le sommeil.", "اشرح التغيّرات الأخيرة في هذا المؤشر وطريقة حسابه وعلاقته بالنوم."),
    "问教练这个变化意味着什么" to InsightTranslation("Ask your coach what this change means", "Demander au coach ce que signifie ce changement", "اسأل المدرب عن معنى هذا التغيّر"),
    "睡眠与其他信号" to InsightTranslation("Sleep and other signals", "Sommeil et autres indicateurs", "النوم والمؤشرات الأخرى"),
    "按日期配对" to InsightTranslation("Paired by date", "Appariés par date", "مطابقة حسب التاريخ"),
    "方法与数据边界" to InsightTranslation("Methods and data limits", "Méthodes et limites des données", "المنهجية وحدود البيانات"),
    "收起" to InsightTranslation("Collapse", "Réduire", "طيّ"),
    "展开" to InsightTranslation("Expand", "Développer", "توسيع"),
    "个人基线：取记录日期前 28 个日历日的有效值中位数，至少 7 条才比较。它不是 Garmin HRV 基线或医学阈值。" to InsightTranslation("Personal baseline: the median of valid values in the 28 calendar days before the record date. Comparison requires at least 7 records. This is neither Garmin’s HRV baseline nor a medical threshold.", "Référence personnelle : médiane des valeurs valides des 28 jours calendaires précédant le relevé. Il faut au moins 7 relevés pour comparer. Ce n’est ni la référence VFC de Garmin ni un seuil médical.", "الخط المرجعي الشخصي: وسيط القيم الصالحة في الأيام التقويمية الـ28 السابقة لتاريخ السجل. تتطلب المقارنة 7 سجلات على الأقل. وهو ليس خط Garmin المرجعي لتقلّب معدل ضربات القلب ولا حدًا طبيًا."),
    "Pearson r：在所选窗口按日期配对，计算 cov(x,y)/(σx·σy)。范围 −1 到 1；零方差或少于 14 对时不显示。0.3 仅作弱线性关系的描述界线，不代表显著性。" to InsightTranslation("Pearson r: records are paired by date within the selected window, using cov(x,y)/(σx·σy). The range is −1 to 1. It is hidden for zero variance or fewer than 14 pairs. The 0.3 boundary only describes a weak linear relationship; it does not indicate statistical significance.", "r de Pearson : les relevés sont appariés par date sur la période choisie, avec cov(x,y)/(σx·σy). Les valeurs vont de −1 à 1. r est masqué si la variance est nulle ou s’il y a moins de 14 paires. Le seuil de 0,3 décrit seulement une relation linéaire faible, sans indiquer de significativité statistique.", "معامل بيرسون r: تُطابق السجلات حسب التاريخ ضمن الفترة المختارة، ويُحسب بالصيغة cov(x,y)/(σx·σy). يتراوح من −1 إلى 1، ولا يظهر عند انعدام التباين أو توفر أقل من 14 زوجًا. حد 0.3 يصف ضعف العلاقة الخطية فقط، ولا يدل على دلالة إحصائية."),
    "睡眠日期沿用 Garmin 记录日期。压力取前一天；HRV 与静息心率取同一记录日期。不同日期的数据不会混用，也不推算缺失值。" to InsightTranslation("Sleep uses the Garmin record date. Stress comes from the preceding day; HRV and resting heart rate use the same record date as sleep. Records are aligned by these dates, and missing values are not estimated.", "La date du sommeil est celle du relevé Garmin. Le stress est celui de la veille ; la VFC et la fréquence cardiaque au repos portent la même date que le sommeil. Les données sont alignées sur ces dates, sans estimation des valeurs manquantes.", "يُستخدم تاريخ سجل Garmin للنوم. يؤخذ الإجهاد من اليوم السابق، وHRV ونبض الراحة من تاريخ سجل النوم نفسه. تُطابق البيانات وفق هذه التواريخ، ولا تُقدّر القيم المفقودة."),
    "睡眠阶段是设备根据心率、HRV 与活动估计的结果。这些信号可能并不独立，不能据此确定没睡好的原因。" to InsightTranslation("The device estimates sleep stages from heart rate, HRV, and movement. These signals may not be independent, so they cannot establish why you slept poorly.", "L’appareil estime les phases du sommeil à partir de la fréquence cardiaque, de la VFC et des mouvements. Ces signaux peuvent être liés entre eux et ne permettent pas d’établir la cause d’une mauvaise nuit.", "يقدّر الجهاز مراحل النوم من النبض وHRV والحركة. قد لا تكون هذه المؤشرات مستقلة عن بعضها، لذلك لا تحدد وحدها سبب سوء النوم."),
    "Garmin：睡眠测量方法" to InsightTranslation("Garmin: how sleep is measured", "Garmin : la mesure du sommeil", "Garmin: كيف يُقاس النوم"),
    "Garmin：HRV 与个人基线" to InsightTranslation("Garmin: HRV and your baseline", "Garmin : VFC et référence personnelle", "Garmin: HRV والخط المرجعي الشخصي"),
    "正在加载你的健康记录" to InsightTranslation("Loading your health records", "Chargement de vos données de santé", "جارٍ تحميل سجلاتك الصحية"),
    "重新加载" to InsightTranslation("Reload", "Recharger", "إعادة التحميل"),
    "关闭" to InsightTranslation("Close", "Fermer", "إغلاق"),
    "返回" to InsightTranslation("Back", "Retour", "رجوع"),
    "查看记录" to InsightTranslation("View records", "Voir les relevés", "عرض السجلات"),
    "数据日期" to InsightTranslation("Record date", "Date des données", "تاريخ البيانات"),
    "方法" to InsightTranslation("Method", "Méthode", "المنهجية"),
    "旅行氛围" to InsightTranslation("Travel atmosphere", "Ambiance de voyage", "أجواء السفر"),
    "蓝瓷与玻璃" to InsightTranslation("Blue tiles & glass", "Azulejos et verre", "بلاط أزرق وزجاج"),
    "仅保存在这部手机上的外观偏好" to InsightTranslation("Appearance preferences saved only on this phone", "Préférences d’apparence enregistrées uniquement sur ce téléphone", "تُحفظ تفضيلات المظهر على هذا الهاتف فقط"),
    "退出登录" to InsightTranslation("Sign out", "Se déconnecter", "تسجيل الخروج"),
    "教练正在分析" to InsightTranslation("Your coach is analyzing", "Le coach analyse vos données", "المدرب يحلّل البيانات"),
    "准备对话" to InsightTranslation("Preparing your conversation", "Préparation de la conversation", "جارٍ إعداد المحادثة"),
    "继续生成回答" to InsightTranslation("Continue generating the answer", "Continuer la réponse", "متابعة إنشاء الإجابة"),
    "你的问题已带上睡眠日期，可编辑后发送" to InsightTranslation("The sleep date is included. Edit your question before sending.", "La date du sommeil est incluse. Vous pouvez modifier la question avant de l’envoyer.", "أُضيف تاريخ النوم إلى سؤالك. يمكنك تعديله قبل الإرسال."),
    "最近的对话" to InsightTranslation("Recent conversations", "Conversations récentes", "المحادثات الأخيرة"),
    "解释睡眠与 HRV 的关系" to InsightTranslation("Explain the link between sleep and HRV", "Expliquer le lien entre sommeil et VFC", "اشرح العلاقة بين النوم وHRV"),
    "为什么昨晚没睡好" to InsightTranslation("Why didn’t I sleep well last night?", "Pourquoi ai-je mal dormi cette nuit ?", "لماذا لم أنم جيدًا الليلة الماضية؟"),
    "训练之后怎么恢复" to InsightTranslation("How can I recover after training?", "Comment récupérer après l’entraînement ?", "كيف أتعافى بعد التدريب؟"),
    "恢复准备度来自 Garmin；各指标按自己的记录日期展示" to InsightTranslation("Readiness comes from Garmin; each metric shows its own record date.", "La préparation vient de Garmin ; chaque indicateur affiche sa propre date de relevé.", "درجة الاستعداد من Garmin؛ ويُعرض كل مؤشر حسب تاريخ سجله."),
    "运动详情" to InsightTranslation("Activity details", "Détails de l’activité", "تفاصيل النشاط"),
    "最高心率" to InsightTranslation("Max HR", "FC maximale", "أقصى نبض"),
    "训练效果" to InsightTranslation("Training effect", "Effet d’entraînement", "تأثير التدريب"),
    "热量" to InsightTranslation("Calories", "Calories", "السعرات الحرارية"),
    "数据由 Garmin 提供" to InsightTranslation("Data provided by Garmin", "Données fournies par Garmin", "البيانات مقدّمة من Garmin"),
    "最新记录" to InsightTranslation("Latest record", "Dernier relevé", "أحدث سجل"),
    "身体电量是最近一次读数，不代表整夜恢复量" to InsightTranslation("Body Battery is the latest reading, not the amount recovered overnight.", "Body Battery affiche la dernière mesure, pas la quantité récupérée pendant la nuit.", "طاقة الجسم هي أحدث قراءة، ولا تمثل مقدار التعافي خلال الليل."),
    "恢复准备度暂不可用" to InsightTranslation("Readiness is not available yet", "Préparation indisponible pour le moment", "درجة الاستعداد غير متاحة بعد"),
    "同步后可查看 Garmin 恢复准备度" to InsightTranslation("Sync to check Garmin readiness", "Synchronisez pour consulter la préparation Garmin", "زامن البيانات للاطلاع على درجة الاستعداد من Garmin"),
    "查看更多运动" to InsightTranslation("See more activities", "Voir plus d’activités", "عرض المزيد من الأنشطة"),
    "当日活动分钟" to InsightTranslation("Active minutes that day", "Minutes actives du jour", "دقائق النشاط في ذلك اليوم"),
    "松开即可同步" to InsightTranslation("Release to sync", "Relâchez pour synchroniser", "أفلت للمزامنة"),
    "拉开，看看蓝瓷" to InsightTranslation("Pull to reveal the blue tiles", "Tirez pour découvrir les azulejos", "اسحب لتكشف البلاط الأزرق"),
    "查看计算依据" to InsightTranslation("See how this is calculated", "Voir le détail du calcul", "اطّلع على طريقة الحساب"),
    "低于你平时的范围" to InsightTranslation("Below your usual range", "Sous votre plage habituelle", "أقل من نطاقك المعتاد"),
    "高于你平时的范围" to InsightTranslation("Above your usual range", "Au-dessus de votre plage habituelle", "أعلى من نطاقك المعتاد"),
    "在你平时的范围内" to InsightTranslation("Within your usual range", "Dans votre plage habituelle", "ضمن نطاقك المعتاد"),
    "共同变化提供线索；原因还需要结合生活记录。" to InsightTranslation("Changes together offer clues. Understanding causes also needs context from your life.", "Les variations communes donnent des pistes. Pour comprendre les causes, il faut aussi tenir compte de votre quotidien.", "التغيّرات المتزامنة تعطي مؤشرات. وفهم الأسباب يحتاج أيضًا إلى سياق من حياتك اليومية."),
    "每个点，都是你的一晚" to InsightTranslation("Each dot is one of your nights", "Chaque point représente l’une de vos nuits", "كل نقطة تمثّل ليلة من لياليك"),
    "你的平时范围" to InsightTranslation("Your usual range", "Votre plage habituelle", "نطاقك المعتاد"),
    "平时范围" to InsightTranslation("Usual range", "Plage habituelle", "النطاق المعتاد"),
    "色带是过去 28 天的平时范围，圆点是这次读数" to InsightTranslation("The band shows your usual range over the preceding 28 days; the dot is this reading.", "La bande indique votre plage habituelle sur les 28 jours précédents ; le point correspond à ce relevé.", "يمثّل الشريط نطاقك المعتاد خلال الأيام الـ28 السابقة، وتمثّل النقطة هذه القراءة."),
    "睡得较久时，这个读数倾向更低" to InsightTranslation("Longer sleep tends to coincide with lower readings", "Un sommeil plus long tend à aller de pair avec des valeurs plus basses", "تميل هذه القراءة إلى الانخفاض مع النوم الأطول"),
    "睡得较久时，这个读数也倾向更高" to InsightTranslation("Longer sleep tends to coincide with higher readings", "Un sommeil plus long tend à aller de pair avec des valeurs plus élevées", "تميل هذه القراءة إلى الارتفاع مع النوم الأطول"),
    "虚线：平时睡眠" to InsightTranslation("Dashed line: usual sleep", "Pointillés : sommeil habituel", "الخط المتقطّع: نومك المعتاد"),
    "这段记录里，关系还不明显" to InsightTranslation("No clear relationship in these records yet", "Pas encore de lien clair dans ces relevés", "لا توجد علاقة واضحة في هذه السجلات بعد"),
    "正在积累可比较的夜晚" to InsightTranslation("Building a history of comparable nights", "Constitution d’un historique de nuits comparables", "نجمع ليالي يمكن مقارنتها"),
    "正在积累你的平时范围" to InsightTranslation("Learning your usual range", "Votre plage habituelle se précise", "نتعرّف على نطاقك المعتاد"),
    "最近 7 晚" to InsightTranslation("Last 7 nights", "7 dernières nuits", "آخر 7 ليالٍ"),
    "查看这晚睡眠" to InsightTranslation("Review this night’s sleep", "Voir cette nuit de sommeil", "راجع نوم هذه الليلة"),
    "当前读数" to InsightTranslation("Current reading", "Mesure actuelle", "القراءة الحالية"),
    "低于你的平时范围" to InsightTranslation("Below your usual range", "Sous votre plage habituelle", "أقل من نطاقك المعتاد"),
    "高于你的平时范围" to InsightTranslation("Above your usual range", "Au-dessus de votre plage habituelle", "أعلى من نطاقك المعتاد"),
    "在你的平时范围内" to InsightTranslation("Within your usual range", "Dans votre plage habituelle", "ضمن نطاقك المعتاد"),
    "读数时间未提供" to InsightTranslation("Reading time unavailable", "Heure de mesure non fournie", "وقت القراءة غير متاح"),
    "恢复的线索" to InsightTranslation("Recovery clues", "Indices de récupération", "مؤشرات التعافي"),
    "回看睡眠、压力与恢复" to InsightTranslation("Review sleep, stress and recovery", "Revoir sommeil, stress et récupération", "راجع النوم والإجهاد والتعافي"),
    "记录日期未提供" to InsightTranslation("Record date unavailable", "Date du relevé non fournie", "تاريخ السجل غير متاح"),
    "平时多在" to InsightTranslation("Usually around", "Habituellement entre", "غالبًا ضمن"),
    "这次读数暂无数据" to InsightTranslation("No data for this reading", "Pas de données pour cette mesure", "لا توجد بيانات لهذه القراءة"),
    "至少需要 7 天记录" to InsightTranslation("At least 7 days of records needed", "Au moins 7 jours de relevés nécessaires", "يلزم توفر سجلات 7 أيام على الأقل"),
    "最近读数" to InsightTranslation("Latest reading", "Dernière mesure", "أحدث قراءة"),
    "色带覆盖此前 28 天中间 50% 的有效读数，不是医学正常范围；竖线为中位数。" to InsightTranslation("The band covers the middle 50% of valid readings in the preceding 28 days, not a medical normal range. The vertical line marks the median.", "La bande couvre les 50 % centraux des mesures valides des 28 jours précédents ; ce n’est pas une plage de normalité médicale. Le trait vertical indique la médiane.", "يغطي الشريط النصف الأوسط من القراءات الصالحة في الأيام الـ28 السابقة، ولا يمثّل نطاقًا طبيًا طبيعيًا. يشير الخط العمودي إلى الوسيط."),
)

internal fun translateInsight(language: AppLanguage, sourceChinese: String): String? {
    val item = insightTranslations[sourceChinese] ?: return null
    return when (language) {
        AppLanguage.CHINESE -> sourceChinese
        AppLanguage.ENGLISH -> item.en
        AppLanguage.FRENCH -> item.fr
        AppLanguage.ARABIC -> item.ar
    }
}
