package com.thegreatnovel.jingyouhealth.ui

import com.thegreatnovel.jingyouhealth.model.AppLanguage

private val sleepLabTexts = mapOf(
    "随机森林" to arrayOf("Random forest", "Forêt aléatoire", "الغابة العشوائية"),
    "你的数据，先给几个候选" to arrayOf("A shortlist from your own records", "Des pistes issues de vos propres données", "قائمة مرشّحة من سجلاتك الشخصية"),
    "载入或同步后自动比较；点一项，就能查看它的曲线。" to arrayOf("Compared automatically after loading or syncing. Tap a setup to see its curves.", "Comparaison automatique après chargement ou synchronisation. Touchez une configuration pour voir ses courbes.", "تُقارَن الإعدادات تلقائيًا بعد التحميل أو المزامنة. اختر إعدادًا لعرض منحنياته."),
    "三阶变化保留给手动探索" to arrayOf("Third differences are available in manual exploration", "Les différences d’ordre trois restent en exploration manuelle", "الفروق من الرتبة الثالثة متاحة للاستكشاف اليدوي"),
    "正在比较你的不同配置" to arrayOf("Comparing setups using your records", "Comparaison de vos configurations", "جارٍ مقارنة الإعدادات باستخدام سجلاتك"),
    "这一模式下暂时没有足够记录支持候选，仍可手动探索。" to arrayOf("There are not enough records to shortlist this mode yet. You can still explore manually.", "Les données ne suffisent pas encore pour proposer des pistes dans ce mode. L’exploration manuelle reste possible.", "لا تكفي السجلات بعد لاقتراح إعدادات لهذا النمط. لا يزال الاستكشاف اليدوي متاحًا."),
    "含共同作用" to arrayOf("With interaction", "Avec interaction", "مع التفاعل"),
    "分别相加" to arrayOf("Additive factors", "Facteurs additifs", "جمع العاملين دون تفاعل"),
    "筛选期" to arrayOf("Selection period", "Période de sélection", "فترة الاختيار"),
    "最近复核" to arrayOf("Recent verification", "Vérification récente", "التحقّق الأخير"),
    "晚" to arrayOf("nights", "nuits", "ليالٍ"),
    "已比较的设置" to arrayOf("Setups compared", "Configurations comparées", "الإعدادات التي قورنت"),
    "仅按较早筛选期排序" to arrayOf("Ranked only on earlier selection data", "Classement fondé uniquement sur la sélection antérieure", "الترتيب يعتمد فقط على فترة الاختيار الأقدم"),
    "误差改善均相对只看上一晚与周末。不同模式分别排序，样本不同也要留意；候选不等于确定原因。" to arrayOf("Improvements are against previous-night and weekend controls. Modes rank separately; sample sizes also matter. These are leads, not established causes.", "Les gains sont comparés au modèle nuit précédente et week-end. Chaque mode est classé séparément ; les tailles d’échantillon comptent aussi. Ce sont des pistes, pas des causes établies.", "التحسّن مقارنة بمرجع الليلة السابقة ونهاية الأسبوع. يُرتّب كل نمط على حدة وحجم العينة مهم أيضًا. هذه قرائن وليست أسبابًا مؤكدة."),
    "记录不足，尚未复核" to arrayOf("Not enough records to verify", "Données insuffisantes pour vérifier", "السجلات لا تكفي للتحقّق"),
    "没有超过简单参考" to arrayOf("Did not beat the simple reference", "Ne dépasse pas la référence simple", "لم يتفوّق على المرجع البسيط"),
    "误差略小" to arrayOf("Slightly lower error", "Erreur légèrement réduite", "خطأ أقل قليلًا"),
    "误差减少" to arrayOf("Error reduced by", "Erreur réduite de", "انخفض الخطأ بنسبة"),
    "也可以自己选一个问题" to arrayOf("Or choose your own question", "Ou choisir votre propre question", "أو اختر سؤالك بنفسك"),
    "正在查看候选配置的预留复核段" to arrayOf("Showing this candidate’s reserved verification period", "Affichage de la période réservée à la vérification", "تعرض هذه النتائج فترة التحقّق المحجوزة لهذا الإعداد"),
    "候选先用前 60% 拟合、中间 20% 筛选；最新 20% 只作复核，不参与排序。复核前会用较早 80% 重新拟合。" to arrayOf("Candidates fit the first 60% and are selected on the middle 20%. The latest 20% only verifies them and never ranks them. Verification refits the earlier 80%.", "Les candidats sont ajustés sur les premiers 60 % et sélectionnés sur les 20 % suivants. Les derniers 20 % servent uniquement à vérifier, jamais à classer. L’ajustement est repris sur les premiers 80 % avant vérification.", "تُبنى الإعدادات من أول 60٪ وتُختار باستخدام 20٪ الوسطى. آخر 20٪ للتحقّق فقط ولا تؤثر في الترتيب. قبل التحقّق يُعاد بناء النموذج على أقدم 80٪."),
    "这组因素暂时无法稳定计算" to arrayOf("This combination cannot be fitted reliably yet", "Cette combinaison ne peut pas encore être ajustée de façon stable", "لا يمكن حساب هذه المجموعة بصورة مستقرة بعد"),
    "记录日期暂不可用" to arrayOf("The record date is not available", "La date de l’observation est indisponible", "تاريخ السجل غير متاح حاليًا"),
    "条件曲线使用因素一的第 10–90 百分位，以及因素二的第 25/75 百分位。有些组合可能并未同时出现过。" to arrayOf("Curves use the first factor’s 10th–90th percentiles and the second’s 25th/75th percentiles. Some combinations may not have occurred together.", "Les courbes utilisent les 10e–90e percentiles du premier facteur et les 25e/75e du second. Certaines combinaisons n’ont peut-être jamais été observées ensemble.", "تستخدم المنحنيات المئينات 10–90 للعامل الأول و25/75 للثاني. قد لا تكون بعض التركيبات قد ظهرت معًا."),
    "睡眠关系实验室" to arrayOf("Sleep relationship lab", "Laboratoire du sommeil", "مختبر علاقات النوم"),
    "探索更多因素与睡眠参数" to arrayOf("Explore more factors and sleep measures", "Explorer d’autres facteurs et mesures", "استكشف عوامل ومقاييس نوم أخرى"),
    "把两个因素放在一起，看睡眠有什么不同" to arrayOf("See how two factors relate to your sleep", "Observer deux facteurs avec votre sommeil", "انظر كيف يرتبط عاملان بنومك"),
    "从一个问题开始" to arrayOf("Start with a question", "Partir d’une question", "ابدأ بسؤال"),
    "活动多的日子，身体压力有关系吗？" to arrayOf("On active days, does body stress matter?", "Les jours actifs, le stress corporel compte-t-il ?", "هل يرتبط إجهاد الجسم بالنوم في الأيام النشطة؟"),
    "训练多久，和训练时的心率一起看" to arrayOf("Workout duration, alongside exercise heart rate", "Durée d’exercice et fréquence cardiaque", "مدة التمرين مع معدل النبض أثناءه"),
    "连着少睡后，身体压力会更值得留意吗？" to arrayOf("After shorter nights, does body stress matter more?", "Après des nuits courtes, le stress compte-t-il davantage ?", "هل يصبح إجهاد الجسم أهم بعد ليالٍ أقصر؟"),
    "想了解什么" to arrayOf("What would you like to understand?", "Que souhaitez-vous comprendre ?", "ما الذي تريد فهمه؟"),
    "因素一" to arrayOf("First factor", "Premier facteur", "العامل الأول"),
    "一起考虑的因素" to arrayOf("Consider alongside", "À considérer ensemble", "العامل المصاحب"),
    "考虑两者的共同作用" to arrayOf("Include their interaction", "Inclure leur interaction", "تضمين التفاعل بينهما"),
    "观察方式" to arrayOf("How to look at it", "Mode d’observation", "طريقة النظر إلى البيانات"),
    "实际读数" to arrayOf("Recorded values", "Valeurs mesurées", "القراءات المسجلة"),
    "每天的变化" to arrayOf("Day-to-day changes", "Variations quotidiennes", "التغيّر اليومي"),
    "变化的变化" to arrayOf("Changes in the changes", "Variation des variations", "تغيّر التغيّر"),
    "三阶变化" to arrayOf("Third differences", "Différences d’ordre trois", "الفروق من الرتبة الثالثة"),
    "同一天" to arrayOf("Same day", "Même jour", "اليوم نفسه"),
    "天前" to arrayOf("days earlier", "jours avant", "أيام قبل"),
    "差分阶数：也可以只看变化" to arrayOf("Difference order: look at changes", "Ordre de différence : observer les variations", "رتبة الفروق: يمكنك النظر إلى التغيّرات"),
    "差分同时用于睡眠结果和两个因素。高阶会减少可用夜晚，也更容易放大噪声。" to arrayOf("The same differencing is applied to sleep and both factors. Higher orders leave fewer usable nights and can amplify noise.", "La même différenciation s’applique au sommeil et aux deux facteurs. Un ordre élevé réduit les nuits utilisables et peut amplifier le bruit.", "تُطبّق الفروق نفسها على النوم والعاملين. الرتب الأعلى تقلّل الليالي المتاحة وقد تضخّم الضوضاء."),
    "因素取睡眠记录之前几天" to arrayOf("How many days before the sleep record?", "Combien de jours avant la nuit ?", "كم يومًا قبل سجل النوم نأخذ العوامل؟"),
    "提前几天与差分阶数是两件事；七天前不是七阶差分。" to arrayOf("Days earlier and difference order are separate. Seven days earlier is not a seventh difference.", "Le décalage en jours et l’ordre de différence sont distincts. Sept jours avant n’est pas une différence d’ordre sept.", "عدد الأيام السابقة ورتبة الفروق أمران مختلفان؛ قبل سبعة أيام لا يعني فرقًا من الرتبة السابعة."),
    "同日因素可能包含醒来后的读数。这里看共同变化，不作为睡前预测。" to arrayOf("Same-day factors may include readings after waking. This shows co-movement, not a prediction made before sleep.", "Les facteurs du même jour peuvent inclure des mesures après le réveil. Il s’agit de variations communes, pas d’une prévision avant le coucher.", "قد تشمل عوامل اليوم نفسه قراءات بعد الاستيقاظ. ننظر هنا إلى التغيّر المشترك، لا إلى تنبؤ قبل النوم."),
    "这个因素在这段记录里变化太少" to arrayOf("This factor varies too little in these records", "Ce facteur varie trop peu sur cette période", "هذا العامل يتغيّر قليلًا جدًا في هذه السجلات"),
    "这项睡眠结果暂时没有足够变化" to arrayOf("This sleep measure does not vary enough yet", "Cette mesure du sommeil ne varie pas assez", "هذا المقياس للنوم لا يتغيّر بما يكفي بعد"),
    "先多积累一些可以对照的夜晚" to arrayOf("We need more comparable nights", "Il faut davantage de nuits comparables", "نحتاج إلى ليالٍ إضافية قابلة للمقارنة"),
    "目前能完整对齐的夜晚" to arrayOf("Nights with complete matching records", "Nuits avec des données complètes et alignées", "الليالي ذات السجلات المكتملة والمتطابقة"),
    "差分、日期提前和缺测都会减少可用记录。训练日心率只在有运动且记录完整的日子使用。" to arrayOf("Differencing, earlier dates and missing readings reduce usable records. Exercise heart rate is used only on days with recorded workouts and complete data.", "Différences, décalages et données manquantes réduisent les observations utilisables. Le pouls d’exercice n’est utilisé que les jours d’entraînement complets.", "الفروق والتواريخ السابقة والقراءات المفقودة تقلّل السجلات المتاحة. يُستخدم نبض التمرين فقط في أيام التمرين ذات البيانات المكتملة."),
    "多看一些日子，先用实际读数" to arrayOf("Use a longer window and recorded values", "Élargir la période et utiliser les mesures", "استخدم فترة أطول والقراءات الأصلية"),
    "这组因素提供了一些额外线索" to arrayOf("These factors add some information", "Ces facteurs apportent quelques indices", "تضيف هذه العوامل بعض المعلومات"),
    "这组因素还没超过简单参考" to arrayOf("These factors have not beaten the simple reference", "Ces facteurs ne dépassent pas encore la référence simple", "لم تتفوّق هذه العوامل على المرجع البسيط بعد"),
    "用较早的夜晚建立关系，再回看之后的记录" to arrayOf("Fit earlier nights, then check later records", "Ajuster sur les premières nuits, puis vérifier les suivantes", "نبني العلاقة من الليالي الأقدم ثم نراجع السجلات اللاحقة"),
    "未参与拟合的夜晚，平均相差" to arrayOf("Average error on nights not used for fitting", "Écart moyen sur les nuits non utilisées pour l’ajustement", "متوسط الخطأ في الليالي التي لم تدخل في بناء النموذج"),
    "越短越贴近记录；这是回看误差，不是原因占比。" to arrayOf("Shorter bars mean closer estimates. This is evaluation error, not a share of the cause.", "Une barre plus courte indique une estimation plus proche. C’est une erreur de validation, pas une part de causalité.", "الشريط الأقصر يعني تقديرًا أقرب للسجل. هذا خطأ المراجعة وليس نسبةً من السبب."),
    "模型与真实记录，贴近吗？" to arrayOf("How close is the model to your records?", "Le modèle suit-il vos observations ?", "ما مدى قرب النموذج من سجلاتك؟"),
    "真实记录" to arrayOf("Recorded", "Observé", "السجل الفعلي"),
    "模型估计" to arrayOf("Model estimate", "Estimation du modèle", "تقدير النموذج"),
    "不同背景下，两条线会怎样变化？" to arrayOf("How does the relationship change with the other factor?", "La relation change-t-elle selon l’autre facteur ?", "كيف تتغيّر العلاقة باختلاف العامل الآخر؟"),
    "较低时" to arrayOf("Lower level", "Niveau plus bas", "عند مستوى أقل"),
    "较高时" to arrayOf("Higher level", "Niveau plus haut", "عند مستوى أعلى"),
    "斜率不同才表示模型中的共同作用；仅仅上下分开不算。" to arrayOf("Different slopes show an interaction in the model. A vertical gap alone does not.", "Des pentes différentes indiquent une interaction dans le modèle. Un simple écart vertical ne suffit pas.", "اختلاف الميل يدلّ على تفاعل في النموذج؛ الفجوة الرأسية وحدها لا تكفي."),
    "加入共同作用后，回看误差更小" to arrayOf("Including the interaction reduced evaluation error", "L’interaction réduit l’erreur de validation", "قلّل تضمين التفاعل خطأ المراجعة"),
    "加入共同作用后，回看还没有更准" to arrayOf("The interaction has not improved evaluation accuracy", "L’interaction n’améliore pas encore la validation", "لم يحسّن التفاعل دقة المراجعة بعد"),
    "曲线来自较早的记录；每次固定其他条件，不代表改变一个因素就会产生这个结果。" to arrayOf("Curves use earlier records with other conditions held fixed. They do not show what changing a factor would cause.", "Les courbes utilisent les premières observations, les autres conditions étant fixes. Elles ne montrent pas l’effet causal d’un changement.", "تستخدم المنحنيات السجلات الأقدم مع تثبيت الشروط الأخرى. لا تُظهر ما سيسبّبه تغيير عامل ما."),
    "方法、样本与数据口径" to arrayOf("Method, sample and data definitions", "Méthode, échantillon et données", "المنهجية والعينة وتعريف البيانات"),
    "先按连续日期差分，再按提前天数对齐。缺一天就留空，不跨缺口计算。" to arrayOf("Difference consecutive dates first, then align earlier factors. Missing days stay missing; gaps are never bridged.", "Calculer d’abord les différences entre jours consécutifs, puis aligner les facteurs antérieurs. Les jours manquants restent vides.", "نحسب الفروق بين الأيام المتتالية أولًا ثم نطابق العوامل السابقة. تبقى الأيام المفقودة فارغة ولا نتجاوز الفجوات."),
    "模型同时考虑上一晚同项睡眠结果和周末。两个因素先用训练段标准化，交互项是标准化后的乘积；使用固定强度的岭回归。" to arrayOf("The model also includes the previous night’s outcome and weekends. Factors are standardized using training data; their product forms the interaction. Ridge strength is fixed.", "Le modèle inclut aussi le résultat de la nuit précédente et le week-end. Les facteurs sont standardisés sur l’entraînement ; leur produit forme l’interaction. La pénalisation ridge est fixe.", "يشمل النموذج أيضًا نتيجة الليلة السابقة وعطلة نهاية الأسبوع. تُوحّد العوامل باستخدام بيانات التدريب ويشكّل حاصل ضربها التفاعل. قوة انحدار ريدج ثابتة."),
    "较早 80% 用于拟合，之后 20% 用于回看；至少保留 10 晚验证。标准化只使用训练段。" to arrayOf("Fit the earlier 80% and evaluate the later 20%, with at least 10 evaluation nights. Scaling uses training data only.", "Ajustement sur les premiers 80 %, validation sur les 20 % suivants, avec au moins 10 nuits de validation. La standardisation utilise uniquement l’entraînement.", "نستخدم أقدم 80٪ لبناء النموذج وآخر 20٪ للمراجعة، مع 10 ليالٍ على الأقل للمراجعة. يعتمد توحيد القيم على التدريب فقط."),
    "回看是逐晚的一步估计，会使用此前已观测的睡眠；不代表提前多晚的独立预测。反复挑选变量后的验证结果也会变得乐观。" to arrayOf("Evaluation is one night at a time, using sleep already observed before it. It is not a multi-night forecast. Repeated variable selection can make evaluation optimistic.", "La validation estime chaque nuit avec le sommeil déjà observé auparavant. Ce n’est pas une prévision sur plusieurs nuits. Des sélections répétées peuvent rendre la validation optimiste.", "تُراجع كل ليلة على حدة باستخدام النوم الذي رُصد قبلها؛ ليس هذا تنبؤًا مستقلًا لعدة ليالٍ. وقد يجعل اختيار المتغيرات مرارًا نتائج المراجعة متفائلة."),
    "拟合夜晚" to arrayOf("Training nights", "Nuits d’ajustement", "ليالي بناء النموذج"),
    "回看夜晚" to arrayOf("Evaluation nights", "Nuits de validation", "ليالي المراجعة"),
    "上一晚睡眠" to arrayOf("Previous night’s sleep", "Sommeil de la nuit précédente", "نوم الليلة السابقة"),
    "周末" to arrayOf("Weekend", "Week-end", "عطلة نهاية الأسبوع"),
    "常数项" to arrayOf("Intercept", "Constante", "الثابت"),
    "标准化模型系数" to arrayOf("Standardized-model coefficients", "Coefficients du modèle standardisé", "معاملات النموذج الموحّد"),
    "这是描述个人历史的简化模型；不计算显著原因、医疗阈值或原因贡献百分比。" to arrayOf("This simplified model describes personal history. It does not identify proven causes, medical thresholds or causal contribution percentages.", "Ce modèle simplifié décrit votre historique. Il n’identifie ni causes prouvées, ni seuils médicaux, ni pourcentages de contribution causale.", "هذا نموذج مبسّط يصف السجل الشخصي. لا يحدّد أسبابًا مثبتة أو حدودًا طبية أو نسب مساهمة سببية."),
    "这些问题从哪里来" to arrayOf("Where these questions come from", "D’où viennent ces questions ?", "من أين جاءت هذه الأسئلة؟"),
    "研究提示，活动与压力、运动强度与时长值得一起观察。这里用你的记录提出假设，不照搬人群研究的结论。" to arrayOf("Research suggests considering activity with stress, and exercise intensity with duration. Your records generate hypotheses; population findings are not personal conclusions.", "La recherche suggère d’examiner activité et stress, intensité et durée ensemble. Vos données servent à formuler des hypothèses, pas à copier les conclusions d’une population.", "تشير الأبحاث إلى فائدة النظر إلى النشاط مع الإجهاد وشدة التمرين مع مدته. نستخدم سجلاتك لطرح فرضيات، لا لنسخ نتائج الدراسات الجماعية."),
    "活动与感知压力：个人内观察研究" to arrayOf("Activity and perceived stress: within-person study", "Activité et stress perçu : étude intra-individuelle", "النشاط والإجهاد المُدرَك: دراسة داخل الفرد"),
    "运动时机与强度：2025 年大样本研究" to arrayOf("Exercise timing and strain: 2025 cohort study", "Horaire et charge d’exercice : cohorte de 2025", "توقيت التمرين وجهده: دراسة واسعة عام 2025"),
    "为什么差分和时间验证要谨慎使用" to arrayOf("Using differences and time-based evaluation carefully", "Utiliser différences et validation temporelle avec soin", "استخدام الفروق والمراجعة الزمنية بحذر"),
    "Garmin 身体压力不是主观心理压力，步数也不是论文中的中高强度运动。睡前训练间隔、咖啡因和酒精尚无完整记录，因此暂不放进模型。" to arrayOf("Garmin stress is not perceived psychological stress, and steps are not the studies’ moderate-to-vigorous activity. Bedtime exercise gaps, caffeine and alcohol lack complete records and are not modeled.", "Le stress Garmin n’est pas le stress psychologique perçu, et les pas ne sont pas l’activité modérée à intense des études. Les intervalles avant le coucher, la caféine et l’alcool ne sont pas modélisés faute de données complètes.", "إجهاد Garmin ليس الإجهاد النفسي المُدرَك، والخطوات ليست النشاط المتوسط إلى الشديد في الدراسات. لا توجد سجلات مكتملة لفاصل التمرين قبل النوم والكافيين والكحول، لذا لا نضمّنها."),
    "请解释这组睡眠关系，区分记录支持的线索与尚待验证的假设，并提出一个容易观察的小问题。" to arrayOf("Explain these sleep relationships, separating evidence in the records from untested hypotheses, and suggest one small question I can observe.", "Expliquez ces relations avec le sommeil en séparant les indices des données et les hypothèses à vérifier, puis proposez une petite question facile à observer.", "اشرح علاقات النوم هذه مع التمييز بين ما تدعمه السجلات والفرضيات التي لم تُختبر، واقترح سؤالًا صغيرًا يسهل ملاحظته."),
    "和教练一起解读这个实验" to arrayOf("Explore this with Coach", "Interpréter avec le coach", "فسّر هذه التجربة مع المدرب"),
    "选择一个因素" to arrayOf("Choose a factor", "Choisir un facteur", "اختر عاملًا"),
    "只看上一晚与周末" to arrayOf("Previous night and weekend only", "Nuit précédente et week-end seuls", "الليلة السابقة ونهاية الأسبوع فقط"),
    "加入选定因素" to arrayOf("With selected factors", "Avec les facteurs choisis", "مع العوامل المختارة"),
    "按你选的阶数观察变化" to arrayOf("Explore your chosen difference order", "Observer l’ordre de différence choisi", "راقب التغيّر حسب رتبة الفروق المختارة"),
    "深睡时长" to arrayOf("Deep-sleep duration", "Durée du sommeil profond", "مدة النوم العميق"),
    "REM 时长" to arrayOf("REM duration", "Durée du sommeil paradoxal", "مدة نوم REM"),
    "深睡占比" to arrayOf("Deep-sleep share", "Part du sommeil profond", "نسبة النوم العميق"),
    "REM 占比" to arrayOf("REM share", "Part du sommeil paradoxal", "نسبة نوم REM"),
    "日间压力" to arrayOf("Daytime body stress", "Stress corporel diurne", "إجهاد الجسم خلال النهار"),
    "夜间 HRV" to arrayOf("Night HRV", "VFC nocturne", "HRV الليلي"),
    "身体电量消耗" to arrayOf("Body Battery drained", "Body Battery consommée", "استهلاك طاقة الجسم"),
    "身体电量补充" to arrayOf("Body Battery charged", "Body Battery rechargée", "شحن طاقة الجسم"),
    "近 3 夜睡眠" to arrayOf("Last 3 nights’ sleep", "Sommeil des 3 dernières nuits", "نوم آخر 3 ليالٍ"),
    "运动时长" to arrayOf("Exercise duration", "Durée d’exercice", "مدة التمرين"),
    "运动平均心率" to arrayOf("Exercise average HR", "FC moyenne d’exercice", "متوسط نبض التمرين"),
    "分" to arrayOf("points", "points", "نقطة"),
    "点" to arrayOf("points", "points", "نقطة"),
    "步" to arrayOf("steps", "pas", "خطوة"),
    "百分点" to arrayOf("percentage points", "points de pourcentage", "نقطة مئوية"),
    "Garmin 压力反映身体信号，不等同于心理压力；默认与下一晚睡眠配对" to arrayOf("Garmin stress reflects body signals, not psychological stress; it is paired with the following night by default.", "Le stress Garmin reflète des signaux corporels, pas le stress psychologique ; il est associé à la nuit suivante par défaut.", "يعكس إجهاد Garmin إشارات الجسم لا الإجهاد النفسي؛ ويُقرن افتراضيًا بالنوم التالي."),
    "每日步数，默认与下一晚睡眠配对" to arrayOf("Daily steps, paired with the following night by default.", "Pas quotidiens, associés à la nuit suivante par défaut.", "الخطوات اليومية، مقترنة افتراضيًا بالنوم التالي."),
    "HRV 与睡眠同时记录，同日关系不能解释为睡前原因" to arrayOf("HRV and sleep are recorded together; a same-day relationship is not a pre-sleep cause.", "VFC et sommeil sont enregistrés ensemble ; leur relation le même jour n’est pas une cause avant le coucher.", "يُسجّل HRV والنوم معًا؛ والعلاقة في اليوم نفسه ليست سببًا سابقًا للنوم."),
    "静息心率是每日汇总，可能与睡眠时段重叠" to arrayOf("Resting HR is a daily summary and may overlap the sleep period.", "La FC au repos est un résumé quotidien pouvant recouvrir la période de sommeil.", "نبض الراحة ملخّص يومي قد يتداخل مع فترة النوم."),
    "Garmin 复合指标中的当天电量消耗，与其他身体信号并不独立" to arrayOf("Daily drain from Garmin’s composite metric is not independent of other body signals.", "La consommation quotidienne de l’indicateur composite Garmin n’est pas indépendante des autres signaux.", "الاستهلاك اليومي في مؤشر Garmin المركّب ليس مستقلًا عن إشارات الجسم الأخرى."),
    "Garmin 复合指标中的电量补充可能包含睡眠恢复，不能当作独立的睡前原因" to arrayOf("Garmin’s composite charge can include overnight recovery and is not an independent pre-sleep cause.", "La recharge composite Garmin peut inclure la récupération nocturne et n’est pas une cause indépendante avant le coucher.", "قد يشمل شحن مؤشر Garmin المركّب التعافي أثناء النوم، وليس سببًا مستقلًا يسبق النوم."),
    "截至记录日连续 3 夜的平均时长，前一天配对时不包含目标睡眠" to arrayOf("Mean duration over 3 consecutive nights through that date. A one-day lag excludes the target night.", "Durée moyenne des 3 nuits consécutives jusqu’à cette date. Un décalage d’un jour exclut la nuit étudiée.", "متوسط مدة 3 ليالٍ متتالية حتى تاريخ السجل؛ الإزاحة يومًا واحدًا تستبعد الليلة المستهدفة."),
    "按运动发生地的日期汇总运动时长" to arrayOf("Exercise duration is summed by its recorded local date.", "La durée d’exercice est totalisée par date locale enregistrée.", "تُجمع مدة التمرين بحسب تاريخه المحلي المسجّل."),
    "同一天所有已记录运动的训练负荷之和" to arrayOf("Sum of training load across recorded workouts that day.", "Somme des charges des exercices enregistrés ce jour-là.", "مجموع حمل التمارين المسجّلة في اليوم نفسه."),
    "按运动时长加权的平均心率，无运动日没有心率值" to arrayOf("Average exercise HR weighted by duration; non-exercise days have no exercise HR value.", "FC moyenne pondérée par la durée ; les jours sans exercice n’ont pas de FC d’exercice.", "متوسط نبض التمرين موزونًا بالمدة؛ لا توجد قيمة لنبض التمرين في الأيام دون تمرين.")
)

internal fun translateSleepLab(language: AppLanguage, source: String): String? {
    val values = sleepLabTexts[source] ?: return null
    return when (language) {
        AppLanguage.CHINESE -> source
        AppLanguage.ENGLISH -> values[0]
        AppLanguage.FRENCH -> values[1]
        AppLanguage.ARABIC -> values[2]
    }
}
